### PR TITLE
removed select category and welcome message

### PR DESCRIPTION
**Pull request by mayperalta**
removed select category and welcome message

### CODE REVIEW

**Review by k-pineda — APPROVED** [review]

**Review by Franko88Bit — APPROVED** [review]
ty

**Review by Franko88Bit — APPROVED** [review]
ty

**Review by Franko88Bit — APPROVED** [review]
ty

**Review by Franko88Bit — APPROVED** [review]
ty

**Review by Franko88Bit — APPROVED** [review]
ty

**Review by k-pineda — APPROVED** [review]

**Review by Franko88Bit — APPROVED** [review]
ty

**Pull request closed without merging**
